using System;
using System.Diagnostics;
using CefSharp;

namespace HtmlHelp.Wpf.Internal;

internal sealed class ChmSchemeHandlerFactory : ISchemeHandlerFactory
{
	public IResourceHandler Create(IBrowser browser, IFrame frame, string schemeName, IRequest request)
	{
		ArgumentNullException.ThrowIfNull(request);

		Debug.WriteLine($"[CefSharp][CHM] Create scheme={schemeName} url={request.Url} resourceType={request.ResourceType}");

		if (!Uri.TryCreate(request.Url, UriKind.Absolute, out var uri))
		{
			Debug.WriteLine($"[CefSharp][CHM] Create failed: invalid uri url={request.Url}");
			return null;
		}

		// We use a fixed domain (`http://chm.local/...`) and encode the document id into the path:
		//   http://chm.local/<documentId>/<chm-relative-path>
		var absolutePath = Uri.UnescapeDataString(uri.AbsolutePath);
		var trimmed = absolutePath.TrimStart('/');
		var slash = trimmed.IndexOf('/', StringComparison.Ordinal);
		if (slash <= 0)
		{
			Debug.WriteLine($"[CefSharp][CHM] Create failed: missing documentId path={absolutePath}");
			return null;
		}

		var documentId = trimmed[..slash];
		var localPath = trimmed[slash..];
		Debug.WriteLine($"[CefSharp][CHM] Create parsed documentId={documentId} localPath={localPath}");

		// Support root-relative URLs generated by HTML inside the CHM.
		// When a page requests e.g. `/images/foo.png`, the resolved URL becomes:
		//   http://chm.local/images/foo.png
		// which lacks the documentId segment.
		if (!ChmDocumentRegistry.TryGet(documentId, out var document) || document == null)
		{
			var referrer = request.ReferrerUrl;
			if (!string.IsNullOrWhiteSpace(referrer)
				&& Uri.TryCreate(referrer, UriKind.Absolute, out var refUri)
				&& refUri.Scheme.Equals("http", StringComparison.OrdinalIgnoreCase)
				&& refUri.Host.Equals("chm.local", StringComparison.OrdinalIgnoreCase))
			{
				var refPath = Uri.UnescapeDataString(refUri.AbsolutePath).TrimStart('/');
				var refSlash = refPath.IndexOf('/', StringComparison.Ordinal);
				if (refSlash > 0)
				{
					var refDocumentId = refPath[..refSlash];
					if (ChmDocumentRegistry.TryGet(refDocumentId, out document) && document != null)
					{
						// Treat the entire path as local CHM path.
						var fallbackLocalPath = absolutePath;
						Debug.WriteLine($"[CefSharp][CHM] Create fallback referrerDocumentId={refDocumentId} localPath={fallbackLocalPath}");
						return new ChmResourceHandler(document, fallbackLocalPath);
					}
				}
			}

			Debug.WriteLine($"[CefSharp][CHM] Create failed: document not found id={documentId} referrer={request.ReferrerUrl}");
			return null;
		}

		return new ChmResourceHandler(document, localPath);
	}
}
